- name: Creating blackbox_exporter user group
  group: name="{{groupId}}"
  become: true

- name: Creating blackbox_exporter user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Install blackbox_exporter
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ version }}/blackbox_exporter-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy blackbox file to bin
  copy:
    src: "/tmp/blackbox_exporter-{{ version }}.linux-amd64/blackbox_exporter"
    dest: "/usr/local/bin/blackbox_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete blackbox_exporter tmp folder
  file:
    path: '/tmp/blackbox_exporter-{{ version }}.linux-amd64'
    state: absent

- name: Creates config directory
  file: 
    path: "/etc/blackbox/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy config file
  copy:
    src: "{{ role_path }}/files/blackbox.yml"
    dest: /etc/blackbox/blackbox.yml

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service

- name: Start blackbox_exporter service
  service:
    name: blackbox_exporter
    state: started
    enabled: yes

- name: Ufw allow blackbox_port
  shell:
    sudo ufw allow 9115

- name: Check if blackbox_exporter emits metrices
  uri:
    url: http://your_ip:9115/metrics
    method: GET
    status_code: 200
