  global:
    resolve_timeout: 1m

  route:
    repeat_interval: 5m
    receiver: 'gmail-notifications'

  receivers:
  - name: 'gmail-notifications'
    email_configs:
    - to: your_email
      from: your_email
      smarthost: smtp.gmail.com:587
      auth_username: your_email
      auth_identity: your_email
      auth_password: your_password
      send_resolved: true